# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'RealmPlayground' do
  pod 'Alamofire', '~> 1.2'
  pod 'RealmSwift', '~> 0.93'
end

target 'RealmPlaygroundTests' do

end

